### ISSUE TITLE
Important change in salmonIPM re: covariates

### ISSUE THREAD

**Issue by ebuhle** [mdscheuerell/AukeCoho#3]
Hey @DavidTallmon, just a heads-up that I realized there was an issue in the `IPM_SMaS_np` Stan code in `salmonIPM` that affects our inference re environmental covariates at the end of yesterday's code-jam session. As part of my efforts to diagnose the parallel-chains error, I had intentionally commented out the lines where the regression predictors enter into [smolt production](https://github.com/ebuhle/salmonIPM/blob/60458cccd0badf8bba0518c35ecef202ded36ea5/inst/stan/IPM_SMaS_np.stan#L263-L264) and [SAR](https://github.com/ebuhle/salmonIPM/blob/60458cccd0badf8bba0518c35ecef202ded36ea5/inst/stan/IPM_SMaS_np.stan#L211-L212), and forgot to restore them before we fit the [`fit_BH_env`](https://github.com/mdscheuerell/AukeCoho/blob/857f7c3b85f6e43b64ac7b7af0a18035482f58be/analysis/auke_coho_ipm.R#L95-L101) model. I've done that now, and pushed the "real" model to [`salmonIPM@ICchinook-models`](https://github.com/ebuhle/salmonIPM/tree/ICchinook-models), so the next time you work on the analysis you should unleash these lines to reinstall the package:

```r
#unleash below to update master branch version of IPM
detach(package:salmonIPM, unload = TRUE)
devtools::install_github("ebuhle/salmonIPM@ICchinook-models")
library("salmonIPM")
```  

I'll try to make sure the package repo is fully functional (for everyone but me) from now on, although I can't guarantee that in the immediate future.

FWIW, there's still nothing going on with stream temp or hatchery releases, but there is a 96% probability that PDO has a positive effect on SAR.

**Comment by DavidTallmon** [comment]
Thanks, Eric.  Seems to work just fine.  Got a warning about $ operator being invalid for atomic vectors in response to line under ##Truncate fish data to non-missing covariate data, but program seems to be working - chains are running.

**Comment by ebuhle** [comment]
Are you using the current version of the script? I seem to recall getting that warning because `env_data` had been converted from a data frame to a matrix, but the script doesn't do that anymore.

**Comment by DavidTallmon** [comment]
Hey Eric.  I'm back to working on this project.  Is working with the package you listed above in this string still the one to use?

**Comment by ebuhle** [comment]
Hi @DavidTallmon, you have two options for installing `salmonIPM` at the moment. One is to use the `master` branch, which is stable and should behave exactly as before. You can do that with

```r
devtools::install_github("ebuhle/salmonIPM")
```  

Alternatively, you could try the `develop` branch which is new and improved in a couple of ways. The biggest change is that I switched over to the "Stan-approved" package structure created with **rstantools**. For the user, the upshot is that the models are now precompiled and start sampling immediately when called. In addition, I finally figured out how to set up the priors on the initial states (spawner abundance and age structure in years `1:max_age`) in a way that fully uses the information in the data. Unfortunately, the one model where this hasn't been implemented yet is `IPM_SMaS_np` (i.e., the one you want) owing to the extra complexity of the juvenile age structure. I plan to do this eventually, but it's not near the top of the priority list. You can install the `develop` branch with

```r
devtools::install_github("ebuhle/salmonIPM@develop")
```  

I would actually be interested to hear if this works, since I'm always building the package from my local copy of the repo rather than installing from GH.

One last note: we still don't have user-specified priors, so that business about the prior scale on the obs error SD (if I'm remembering correctly) may still be an issue.

**Comment by DavidTallmon** [comment]
Looks like the former command worked to install from the master branch , but the latter yielded the following from the develop branch after scolding me for not have the version of Rtools compatible with R 3.5.1 and then successfully unpacking a few things:
* installing *source* package 'salmonIPM' ...
Warning in system("sh ./configure.win") : 'sh' not found
ERROR: configuration failed for package 'salmonIPM'
* removing 'C:/Users/datallmon/R_LIBS/salmonIPM'
* restoring previous 'C:/Users/datallmon/R_LIBS/salmonIPM'
In R CMD INSTALL
Installation failed: Command failed (1)

Hope that's helpful.

**Comment by ebuhle** [comment]
Hmm. Well, do you have Rtools35 installed? (FYI, the current version of R is 4.0.2 and there's a new version of the toolchain [Rtools40] to go with R 4.x, so I'd suggest upgrading anyway.)

If so, then maybe you should try the suggestion [here](https://github.com/r-lib/rlang/issues/661) to use `remotes::install_github()` instead of `devtools::install_github()`, even though it sounds like the issue described in that thread has since been fixed.

That said, I don't see why this problem, whatever it is, would only affect the `develop` branch, which makes me suspicious that installation from `master` is in fact succeeding. To be certain, try removing your existing installation of **salmonIPM** before installing from GH.

**Comment by DavidTallmon** [comment]
OK.  I've updated my R version and re-installed everything successfully
except for openssl and backports.  Those seem to give me grief whether I
try to install from the source packages or get binaries.  Not sure if I'm
safe to go in and remove older versions of openssl and backports as wants
me to.....

> devtools::install_github("ebuhle/salmonIPM")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo ebuhle/salmonIPM@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All
2: CRAN packages only
3: None
4: backports (1.1.7 -> 1.1.8) [CRAN]
5: openssl   (1.4.1 -> 1.4.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
backports (1.1.7 -> 1.1.8) [CRAN]
openssl   (1.4.1 -> 1.4.2) [CRAN]
Installing 2 packages: backports, openssl
Installing packages into ‘C:/Users/datallmon/R_LIBS’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions
  are later:
          binary source needs_compilation
backports  1.1.7  1.1.8              TRUE
openssl    1.4.1  1.4.2              TRUE

installing the source packages ‘backports’, ‘openssl’

trying URL 'https://cran.rstudio.com/src/contrib/backports_1.1.8.tar.gz'
Content type 'application/x-gzip' length 18047 bytes (17 KB)
downloaded 17 KB

trying URL 'https://cran.rstudio.com/src/contrib/openssl_1.4.2.tar.gz'
Content type 'application/x-gzip' length 1204168 bytes (1.1 MB)
downloaded 1.1 MB

'\\sync-al\files$\JD-880061-A2\datallmon\Desktop\RStudioPractice'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
ERROR: failed to lock directory 'C:/Users/datallmon/R_LIBS' for modifying
Try removing 'C:/Users/datallmon/R_LIBS/00LOCK-backports'
Error: Failed to install 'salmonIPM' from GitHub:
  (converted from warning) installation of package ‘backports’ had non-zero
exit status
> devtools::install_github("ebuhle/salmonIPM")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo ebuhle/salmonIPM@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All
2: CRAN packages only
3: None
4: backports (1.1.7 -> 1.1.8) [CRAN]
5: openssl   (1.4.1 -> 1.4.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
4
backports (1.1.7 -> 1.1.8) [CRAN]
Installing 1 packages: backports
Installing package into ‘C:/Users/datallmon/R_LIBS’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version
  is later:
          binary source needs_compilation
backports  1.1.7  1.1.8              TRUE

trying URL '
https://cran.rstudio.com/bin/windows/contrib/4.0/backports_1.1.7.zip'
Content type 'application/zip' length 81641 bytes (79 KB)
downloaded 79 KB

package ‘backports’ successfully unpacked and MD5 sums checked
Error: Failed to install 'salmonIPM' from GitHub:
  (converted from warning) cannot remove prior installation of package
‘backports’

**Comment by ebuhle** [comment]
> Enter one or more numbers, or an empty line to skip updates:

You should be fine skipping those updates. You can also use the `upgrade = FALSE` argument to `install_github()` to skip all updates.

**Comment by DavidTallmon** [comment]
Hmm.  Now it seems to be telling me there is no backports package....

detach(package:salmonIPM, unload = TRUE)
Error in detach(package:salmonIPM, unload = TRUE) :
  invalid 'name' argument
> devtools::install_github("ebuhle/salmonIPM",upgrade=FALSE)
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’
